#!/bin/bash

echo "Downloading previous ccache . . . . . ."

cd /tmp
curl https://transfer.sh/j21pG/ccache-fluid-1-4-fix-1.tar.gz -o ccache-fluid-1-4-fix-1.tar.gz
time tar xf ccache-fluid-1-4-fix-1.tar.gz
rm -rf ccache-fluid-1-4-fix-1.tar.gz
