#!/bin/bash

cd /tmp

date=`date +%Y%m%d`

# Compress function with pigz for faster compression
com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz ccache
}

time com ccache-havoc-4-5-1 1 # Compression level 1, its enough

up(){
	curl --upload-file $1 https://transfer.sh/
}

up ccache-havoc-4-5-1.tar.gz
